### ISSUE TITLE
featureGroup layers not working in Leaflet 1.0.0-beta.2 ?

### ISSUE THREAD

**Issue by DrYSG** [elesdoar/leaflet-control-orderlayers#10]
I am not sure why, but when I substitute your control in for the standard L.control.layers I see all the base maps, but only one of the overlay layers shows. A picture is worth a 1,000 words (as is a code sample):

commenting out the standard control and it all works just fine. Oh yes, I am using  Leaflet 1.0.0-beta.2 and perhaps that is the issue (Chrome).

Here is one idea. The carLayer is actually a L.featureGroup, with a marker in it.

```
            var baseMaps = {
                "OSM Light": osmLight,
                "OSM Satellite": osmSatellite,
                "OSM Bold": osmComic
            };
            var overlayMaps = {
                "MCity": mapLayer,
                "Live Car": carLayer
            };

            var controls = L.control.orderlayers(baseMaps, overlayMaps, { collapsed: false });
            
            //var controls = L.control.layers(baseMaps, overlayMaps, { collapsed: false });
            controls.addTo(theMap);
```

![croppercapture 1](https://cloud.githubusercontent.com/assets/2865368/11251699/7ae41688-8e00-11e5-9b35-2cd57bd53b9a.jpg)

**Comment by elesdoar** [comment]
It will resolve in #9

**Comment by DrYSG** [comment]
@elesdoar  Thank you greatly. Any chance of letting others try out this branch before hand?

**Comment by elesdoar** [comment]
New beta release for leaflet 1.0.x, please try with: https://github.com/elesdoar/leaflet-control-orderlayers/releases/tag/v1.0.0-beta1
